# -*- coding: utf-8 -*-
"""create_mock_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yte6ZMESYbdfLzQHskPhEmRCwBYuf0Uy
"""

import pandas as pd

countries_db = pd.DataFrame()

countries_db['Country'] = ['Germany','China','South Korea','France','Ghana','United States','Italy','Russia','India','Austria']
countries_db['Capital'] = ['Berlin','Peking','Seoul','Paris','Accra','Washington, D.C.','Rom','Moskau','New-Delhi','Wien']
countries_db['Continent'] = ['Europe','Asia','Asia','Europe','Afrika','North America','Europe',['Europe','Asia'],'Asia','Europe']
countries_db['Leader'] = ['Olaf Scholz','Xi Jinping','Yoon Suk Yeol','Emmanuel Macron','Nana Akufo-Addo','Joe Biden','Giorgia Meloni','Wladimir Putin','Droupadi Murmu','Karl Nehammer']
countries_db['Country_ISO_Code_2_Dig'] = ['DE','CN','KR','FR','GH','US','IT','RU','IN','AT']
countries_db['Country_ISO_Code_3_Dig'] = ['DEU','CHN','KOR','FRA','GHA','USA','ITA','RUS','IND','AUT']
countries_db['Population'] = [81802257,1330044000,48422644,64768389,24339838,310232863,60340328,140702000,1173108018,8205000]
countries_db['Male_Height_AVG'] = [180.28,175.66,175.52,178.60,170.30,176.94,174.42,176.65,166.50,178.52]
countries_db['Female_Height_AVG'] = [166.18,163.46,163.23,164.49,158.86,163.31,161.81,164.52,155.18,166.93]
countries_db['Official_Language'] = ['German','Standard Chinese','Korean','French','English','English','Italian','Russian','Hindi','German']

#create based on a pattern sub_tables with headers from the main_table
#pattern: list[list[int]] , list of header indices
#main_table: pd.DataFrame
def create_sub_tables(pattern,main_table):
    headers = list(main_table.columns)
    sub_tables = []

    for p in pattern:
        tmp_table = pd.DataFrame()
        file_name = 'countries'

        for i in p:
            tmp_header = headers[i]
            file_name += '_' + tmp_header

            tmp_table[tmp_header] = main_table[tmp_header]

        sub_tables.append(tmp_table)
        tmp_table.to_csv(file_name)

    return sub_tables

patterns = [[0,1,3],[0,1,2],[0,3],[0,4,5],[0,2,6],[0,7,8],[0,9],[0,3,9],[0,1,3,4,9],[4,6],[5,7,8],[4,9]]

create_sub_tables(patterns,countries_db)

